apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: demo-apps
  source:
    path: 02-developers/overlays/cicd
    repoURL: https://github.com/pittar-gitops/99-gitops-demo.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
