apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
    - type: "Container"
      max:
        cpu: "1" 
        memory: "512Mi" 
      min:
        cpu: "100m" 
        memory: "256Mi" 
      default:
        cpu: "200m" 
        memory: "256Mi" 
      defaultRequest:
        cpu: "200m" 
        memory: "256Mi" 
