apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: petlinic
    name: petclinic-build
  name: petclinic-build
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: 'petclinic:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: redhat-openjdk18-openshift:1.5
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers: []
status:
  lastVersion: 0
