apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-test-config
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: demo-config
  source:
    path: 01-admins/overlays/03-petclinic-test-admin-config
    repoURL: https://github.com/pittar-gitops/99-gitops-demo.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
