apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cicd
bases:
- ../../base/01-cicd-admin-config
resources:
- 01-namespace.yaml
patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: RoleBinding
    name: system:image-puller
  path: jenkins-image-puller-rolebinding-patch.yaml